services:
  cutauto:
    image: gogoshine/cutauto:latest
    container_name: cutauto
    platform: linux/amd64
    ports:
      - "30000:30000"
    volumes:
      - ./html/output:/app/output  # 挂载配置文件目录
      #- /etc/localtime:/etc/localtime:ro  # 挂载主机时区
      #- /etc/timezone:/etc/timezone:ro    # 挂载时区名称（可选）
    environment:
      # 草稿下载URL
      - DRAFT_URL=http://127.0.0.1/openapi/capcut-mate/v1/get_draft
      # 用于将容器内部的文件路径转成URL，本质是将/app/替换成DOWNLOAD_URL得到下载路径
      - DOWNLOAD_URL=http://127.0.0.1/
    restart: unless-stopped  # 除非手动停止，否则总是重启容器

  capcut-mate:
    image: gogoshine/capcut-mate:latest
    container_name: cutauto-capcut-mate
    platform: linux/amd64
    ports:
      - "30001:30000"
    volumes:
      - ./html/output:/app/output  # 挂载配置文件目录
      #- /etc/localtime:/etc/localtime:ro  # 挂载主机时区
      #- /etc/timezone:/etc/timezone:ro    # 挂载时区名称（可选）
    environment:
      # 草稿下载URL
      - DRAFT_URL=http://127.0.0.1/openapi/capcut-mate/v1/get_draft
      # 用于将容器内部的文件路径转成URL，本质是将/app/替换成DOWNLOAD_URL得到下载路径
      - DOWNLOAD_URL=http://127.0.0.1/
    restart: unless-stopped

  nginx:
    image: gogoshine/nginx:latest
    container_name: cutauto-nginx
    ports:
      - "80:80"
    environment:
      - PROXY_PASS_URL_1=http://127.0.0.1:30000/openapi/cutauto/
      - PROXY_LOCATION_1=/openapi/cutauto/
      - PROXY_PASS_URL_2=http://127.0.0.1:30001/openapi/capcut-mate/
      - PROXY_LOCATION_2=/openapi/capcut-mate/
    volumes:
      - ./html:/usr/share/nginx/html
    restart: unless-stopped